site_name: Future Simulator
nav:
    - Home: 'index.md'
    - 'Requirements': 'requirements.md'
    - 'Installation': 'installation.md'
    - 'User Guide':
        - 'Setup Connection':
            - 'Serial': '.\User Guide\Connecting to Microcontroller\Serial.md'
            - 'TCP': '.\User Guide\Connecting to Microcontroller\TCP.md'
            - 'UDP': '.\User Guide\Connecting to Microcontroller\UDP.md'
        - 'Sending Commands': '.\User Guide\Commands and Response\sending-commands.md'
        - 'Receiving Data': '.\User Guide\Commands and Response\receiving-data-from-mcu.md'
        - 'Application Logs': '.\User Guide\Commands and Response\accessing-app-logs.md'

        - 'Logging MCU Data':
            - 'Generating Log Files' : '.\User Guide\Logging\creating-logs.md'
            - 'Exporting Log Files' : '.\User Guide\Logging\exporting-logs.md'
    - About:
        - 'License': 'license.md'
        - 'Release Notes': 'release-notes.md'

theme:
      name: readthedocs
      nav_style: dark
      locale: en
      navigation_depth: 5
      shortcuts:
                help: 191    # ?
                next: 78     # n
                previous: 80 # p
                search: 83   # s
      sticky_navigation: True
      include_homepage_in_sidebar: True
      logo: './images/future.png'