[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "futuresimulator"
authors = [{name = "Stanley Ezeh", email = "stanley.ezeh@gmail.com"}]
dynamic = ["version", "description"]
